# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ premake-build ]
  pull_request:
    branches: [ premake-build ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-on-linux:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install submodules
        run: git submodule update --init
    
      - name: Install deps
        run: sudo apt-get install libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev
      
      - name: Setup premake
        uses: abel0b/setup-premake@v2.1
        with:
          version: "5.0.0-beta1"
          
      - name: Generate gmake2 files
        run: premake5 gmake2
        
      - name: Build project
        run: make
      
  build-on-macos:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install submodules
        run: git submodule update --init
      
      - name: Setup premake
        uses: abel0b/setup-premake@v2.1
        with:
          version: "5.0.0-beta1"
          
      - name: Generate Xcode4 files
        run: premake5 xcode4
        
      - name: Build project
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          workspace: NightlyEngine.xcworkspace
          scheme: NightlyEditor
          destination: platform=macOS
          action: build
        
  build-on-windows:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Use MSVC
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Install submodules
        run: git submodule update --init
      
      - name: Setup premake
        uses: abel0b/setup-premake@v2.1
        with:
          version: "5.0.0-beta1"
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
          
      - name: Generate Visual Studio 2022 files
        run: premake5 vs2022
        
      - name: Build project
        run: msbuild NightlyEngine.csproj
